---
- name: Installing andrewrothstein.epel
  ansible.builtin.include_role:
    name: andrewrothstein.epel
- name: Installing screen OS package
  become: true
  become_user: root
  ansible.builtin.package:
    name: screen
    state: present
